### ISSUE TITLE
Use of Comments

### ISSUE THREAD

**Issue by mml1** [jahdroid/codecademy-project-3-the-scoop#1]
(Great!) Fantastic use of comments! Your code is easy to read and navigate. I can easily tell where you made changes. 

https://github.com/jahdroid/codecademy-project-3-the-scoop/blob/master/server.js#L54-L55
https://github.com/jahdroid/codecademy-project-3-the-scoop/blob/master/server.js#L85-L87
https://github.com/jahdroid/codecademy-project-3-the-scoop/blob/master/server.js#L110-L112
https://github.com/jahdroid/codecademy-project-3-the-scoop/blob/master/server.js#L133-L135
https://github.com/jahdroid/codecademy-project-3-the-scoop/blob/master/server.js#L155-L157
https://github.com/jahdroid/codecademy-project-3-the-scoop/blob/master/server.js#L177-L179

**Comment by jahdroid** [comment]
Thanks :bowtie:
