### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by mml1** [jahdroid/codecademy-project-3-the-scoop#5]
[Exceeds Expectations] Phenomenal work! Your code is beautiful and easy to navigate. Congrats on completing the bonus. You have a solid understanding of the foundations.

From what I see here, I think you are more than ready to tackle larger projects. I would recommend looking into validations, if you want more of a challenge. By validations, I mean checking to see if the user actually put in an url for the link field. Besides checking to see if the user put something in the link field, see if you can make sure that the user's input looks like a link. If the user's input does not look like a link, what sort of error message would you send?

**Comment by jahdroid** [comment]
Thanks for the compliment!

I've checked the "Article.js" to see if I can implement the URL validation. The code is written in React and I'm not yet familiar with the React syntax. So, I will not keep on going with the challenge and will continuing with the course.
